# Generated by Django 4.1.7 on 2023-04-06 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='mylab_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='reporting_business_unit',
            field=models.CharField(choices=[('OTC', 'OTC'), ('IVD', 'IVD'), ('HTP', 'HTP')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='whatsapp_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesrepresentative',
            name='reporting_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.reportingmanager'),
        ),
    ]
