# Generated by Django 4.1.7 on 2023-04-06 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_salesrepresentative_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='age',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='reporting_business_unit',
            field=models.CharField(choices=[('OTC', 'OTC'), ('IVD', 'IVD'), ('HTP', 'HTP')], max_length=10),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='reporting_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.reportingmanager'),
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='whatsapp_number',
            field=models.CharField(max_length=20),
        ),
    ]
