# Generated by Django 4.1.7 on 2023-04-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_salesrepresentative_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepresentative',
            name='zone',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('South', 'South'), ('North', 'North')], max_length=6),
        ),
    ]
