# Generated by Django 4.1.7 on 2023-04-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_salesrepresentative_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('drug_license_number', models.CharField(max_length=100, null=True)),
                ('p_type', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('is_owner', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('contact_person_designation', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('is_online_friendly', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=4)),
            ],
        ),
    ]
