# Generated by Django 4.1.7 on 2023-04-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('master_d', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.AddField(
            model_name='order',
            name='order_book_image',
            field=models.ImageField(null=True, upload_to='order_book_images'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy'),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.ManyToManyField(to='api.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='distributer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.distributor'),
        ),
    ]
