# Generated by Django 4.1.7 on 2023-04-08 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inventory_pharmacy_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='distributer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.distributor'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_book_image',
            field=models.ImageField(upload_to='order_book_images'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy'),
        ),
    ]
