# Generated by Django 4.1.7 on 2023-04-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_distributer_alter_order_order_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='email',
        ),
        migrations.RemoveField(
            model_name='salesrepresentative',
            name='password',
        ),
    ]
