# Generated by Django 4.1.7 on 2023-04-25 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_order_distributer_alter_order_order_book_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_book_image',
        ),
        migrations.CreateModel(
            name='OrderBookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='order_book_images')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_book_images', to='api.order')),
            ],
        ),
    ]
