# Generated by Django 4.1.7 on 2023-04-25 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_salesrepresentative_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_name',
        ),
    ]
