# Generated by Django 4.1.7 on 2023-04-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_order_delivery_date_remove_order_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_ids',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
