# Generated by Django 4.1.7 on 2023-04-25 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_rename_order_ids_order_order_item_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_book_image',
            field=models.URLField(),
        ),
    ]
