# Generated by Django 4.1.7 on 2023-04-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_order_order_item_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='inventory',
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='inventory',
            field=models.ManyToManyField(to='api.inventory'),
        ),
    ]
