# Generated by Django 4.1.7 on 2023-04-25 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_pharmacy_inventory_pharmacy_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacy',
            old_name='inventory',
            new_name='inventories',
        ),
    ]
