# Generated by Django 4.1.7 on 2023-04-26 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_category_competitorproduct_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='distributer',
            new_name='distributor',
        ),
    ]
