# Generated by Django 4.1.7 on 2023-04-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='pack_size',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
