# Generated by Django 4.1.7 on 2023-04-26 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_order_order_book_image_orderbookimage'),
        ('api', '0026_rename_quantity_orderitem_pack_size_orderitem_units'),
    ]

    operations = [
    ]
