# Generated by Django 4.1.7 on 2023-04-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_inventory_pharmacy_inventory copy'),
        ('api', '0027_merge_20230426_1813'),
    ]

    operations = [
    ]
