# Generated by Django 4.1.7 on 2023-04-26 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_salesrepresentative_gender_and_more copy'),
        ('api', '0028_merge_20230426_1815'),
    ]

    operations = [
    ]
