# Generated by Django 4.1.7 on 2023-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20230426_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacy',
            name='inventory',
        ),
        migrations.AddField(
            model_name='order',
            name='order_book_image',
            field=models.URLField(default='http://139.59.32.100:8000/orders/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesrepresentative',
            name='mylab_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='OrderBookImage',
        ),
    ]
