# Generated by Django 4.1.7 on 2023-04-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_pharmacy_inventory_order_order_book_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic_registration_proof',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo_id_proof',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registration_proof',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo',
            field=models.URLField(),
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_new_marketing_material', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('marketing_material_image', models.URLField(null=True)),
                ('got_orders', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=5)),
                ('order_book_image', models.URLField(null=True)),
                ('pharmacy_image', models.URLField(null=True)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.distributor')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pharmacy')),
                ('product', models.ManyToManyField(to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='orderitem',
            name='working',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='api.working'),
        ),
    ]
