# Generated by Django 4.1.7 on 2023-05-02 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_doctor_clinic_registration_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('working', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geotags', to='api.pharmacy')),
            ],
        ),
    ]
