# Generated by Django 4.1.7 on 2023-05-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_geotag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='geotag',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
    ]
