# Generated by Django 4.1.7 on 2023-05-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_geotag_latitude_alter_geotag_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='working',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geotag', to='api.pharmacy'),
        ),
    ]
