# Generated by Django 4.1.7 on 2023-05-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_geotag_working'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geotag',
            name='working',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geotag', to='api.working'),
        ),
    ]
